server:
  servlet:
    context-path: /demo
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maven_pro?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.lp.bean


logging:
  level:
    com:
      lp:
        mapper : debug


#logging:
#  config: classpath:log4j2.xml