spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maven_pro
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


logging:
  config: classpath:log4j2.xml


server:
  context-path: /demo
  port: 8080