package com.lp.bean;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by CPR161 on 2016-12-16.
 */
@Entity
@Table(name = "user")
public class User {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @NotNull
    private String email;
    @NotNull
    private String name;
    public User() { }
    public User(long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}